-- AlterTable
ALTER TABLE `PostLink` ADD COLUMN `type` ENUM('EXPLICIT', 'FRONT_MATTER', 'WIKI_LINK') NOT NULL DEFAULT 'EXPLICIT';

-- AlterTable
ALTER TABLE `Project` ADD COLUMN `tags` VARCHAR(191) NULL;
